export type Incident = {
  id: string
  title: string
  date: string
  location: string
  country: string
  lat: number
  lng: number
  shape: string
  duration: string
  description: string
  credibility: number
  classification: string
  military: boolean
  radarConfirmed: boolean
  witnesses: number
  source: string
  tags: string[]
  videoId?: string        // YouTube video ID of officially released footage
  videoTitle?: string     // Label shown on the video
  videoSource?: string    // Who released it
}

export const INCIDENTS: Incident[] = [
  {
    id: "INC-001",
    title: "USS Nimitz Tic-Tac Encounter",
    date: "2004-11-14",
    location: "Pacific Ocean, 100mi W of San Diego",
    country: "USA",
    lat: 33.77, lng: -119.5,
    shape: "Elongated Oval",
    duration: "5 minutes",
    description: "Navy F/A-18F pilots from USS Nimitz encountered a 40-foot white object shaped like a Tic-Tac moving erratically at low altitude. Object descended from 80,000ft to near sea level in seconds. No visible propulsion, no wings, no exhaust. Confirmed by FLIR targeting pod and multiple pilots.",
    credibility: 97, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 6, source: "Pentagon / AARO",
    tags: ["FLIR Video", "Multi-Witness", "Radar Confirmed", "Declassified"],
    videoId: "6rWOtrke0HY",
    videoTitle: "FLIR1 — Official UAP Footage Released by US Government (Tic-Tac)",
    videoSource: "To The Stars Academy / US DoD — Officially released Apr 27, 2020",
  },
  {
    id: "INC-002",
    title: "USS Roosevelt Gimbal Incident",
    date: "2015-03-04",
    location: "East Coast, Atlantic Ocean",
    country: "USA",
    lat: 31.5, lng: -74.2,
    shape: "Rotating Disc",
    duration: "2 minutes",
    description: "F/A-18 pilots recorded an object rotating against the wind at high altitude. Object appeared to defy aerodynamic laws. Captured on Advanced Targeting Forward-Looking Infrared (ATFLIR). No thermal exhaust detected. Object maintained speed and altitude effortlessly.",
    credibility: 95, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 4, source: "Pentagon / AARO",
    tags: ["FLIR Video", "Declassified", "Military"],
    videoId: "tf1uLwUTDA0",
    videoTitle: "GIMBAL — Official UAP Footage Released by US Government",
    videoSource: "To The Stars Academy / US DoD — Officially released Apr 27, 2020",
  },
  {
    id: "INC-002B",
    title: "USS Roosevelt GoFast Incident",
    date: "2015-02-21",
    location: "East Coast, Atlantic Ocean",
    country: "USA",
    lat: 30.8, lng: -73.5,
    shape: "Unknown — Radar Track",
    duration: "~1 minute",
    description: "A second ATFLIR video from the same USS Roosevelt deployment shows a small object traveling at extraordinarily low altitude and high speed over the ocean surface. Pilots struggle to lock onto it. The object appears to move faster than anything in the US inventory at the time. Released alongside the Gimbal video by DoD in April 2020.",
    credibility: 95, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 3, source: "Pentagon / DoD — Official Release",
    tags: ["FLIR Video", "Declassified", "Military", "Hypersonic"],
    videoId: "wxVRg7LLaQA",
    videoTitle: "GOFAST — Official UAP Footage Released by US Government",
    videoSource: "To The Stars Academy / US DoD — Officially released Apr 27, 2020",
  },
  {
    id: "INC-003",
    title: "Malmstrom AFB ICBM Shutdown",
    date: "1967-03-16",
    location: "Malmstrom AFB, Montana",
    country: "USA",
    lat: 47.51, lng: -111.18,
    shape: "Glowing Disc",
    duration: "~30 minutes",
    description: "Ten Minuteman I ICBMs at Oscar Flight went offline simultaneously while security personnel reported a glowing red disc hovering near the front gate. All missiles lost strategic alert. Declassified 2010. Robert Salas (launch officer) testified to Congress in 2021.",
    credibility: 88, classification: "Unexplained", military: true, radarConfirmed: false,
    witnesses: 12, source: "Declassified USAF Documents",
    tags: ["Nuclear Site", "Declassified", "Congressional Testimony"],
  },
  {
    id: "INC-004",
    title: "Phoenix Lights Incident",
    date: "1997-03-13",
    location: "Phoenix, Arizona",
    country: "USA",
    lat: 33.44, lng: -112.07,
    shape: "V-Shaped Formation",
    duration: "3 hours",
    description: "Thousands of witnesses across Nevada and Arizona reported a massive V-shaped formation of lights moving silently overhead. Object was estimated at over 1 mile wide. Governor Fife Symington initially mocked the report, later admitted he personally witnessed the object and described it as not of this world.",
    credibility: 85, classification: "Unexplained", military: false, radarConfirmed: false,
    witnesses: 10000, source: "NUFORC / State Records",
    tags: ["Mass Sighting", "Governor Witness", "Formation"],
    videoId: "bvKLeaPWPyw",
    videoTitle: "Phoenix Lights 1997 — Original Witness Footage",
    videoSource: "Civilian footage — 10,000+ witnesses, largest mass sighting in US history",
  },
  {
    id: "INC-005",
    title: "JAL Flight 1628 Encounter",
    date: "1986-11-17",
    location: "Skies over Alaska",
    country: "USA",
    lat: 63.5, lng: -148.0,
    shape: "Massive Walnut-Shaped",
    duration: "50 minutes",
    description: "Japanese Airlines cargo flight 1628 en route from Paris to Tokyo reported a massive object the size of two aircraft carriers pacing the aircraft. Captain Terauchi filed official report with FAA. FAA radar confirmed secondary target. Incident investigated by FAA and NTSB.",
    credibility: 90, classification: "Unexplained", military: false, radarConfirmed: true,
    witnesses: 3, source: "FAA Official Records",
    tags: ["Aviation", "FAA Radar", "Official Report"],
  },
  {
    id: "INC-006",
    title: "O'Hare Airport Disc Sighting",
    date: "2006-11-07",
    location: "O'Hare International Airport, Chicago",
    country: "USA",
    lat: 41.97, lng: -87.91,
    shape: "Dark Disc",
    duration: "5 minutes",
    description: "United Airlines employees and pilots reported a grey, metallic disc hovering over Gate C-17. Object shot upward at high speed leaving a hole in cloud cover. FAA and United Airlines initially denied the incident. Later confirmed by FAA recordings obtained through FOIA.",
    credibility: 86, classification: "Unexplained", military: false, radarConfirmed: false,
    witnesses: 14, source: "FAA FOIA / Chicago Tribune",
    tags: ["Aviation", "FOIA", "Multi-Witness"],
  },
  {
    id: "INC-007",
    title: "Rendlesham Forest Incident",
    date: "1980-12-27",
    location: "RAF Woodbridge / Bentwaters, Suffolk",
    country: "UK",
    lat: 52.09, lng: 1.44,
    shape: "Triangular Craft",
    duration: "Multiple nights",
    description: "US Air Force personnel at RAF Woodbridge in England reported a series of unexplained lights and a landed craft in Rendlesham Forest. Deputy Base Commander Lt. Col. Charles Halt recorded his observations on audio tape. Physical landing marks and radiation levels documented. UK Ministry of Defence investigated.",
    credibility: 91, classification: "Unexplained", military: true, radarConfirmed: false,
    witnesses: 80, source: "UK Ministry of Defence / USAF",
    tags: ["Military", "Landing Marks", "Radiation", "UK MOD"],
  },
  {
    id: "INC-008",
    title: "2019 USS Omaha USO Encounter",
    date: "2019-07-15",
    location: "Pacific Ocean off San Diego",
    country: "USA",
    lat: 32.5, lng: -118.8,
    shape: "Spherical",
    duration: "~90 minutes",
    description: "USS Omaha combat information center tracked multiple unmanned aerial vehicles (UAVs/UAPs) using ship's radar and visual. Video shows pyramid-shaped objects hovering above the ship. Objects eventually descended into ocean and disappeared. Classified until leaked to filmmaker Jeremy Corbell in 2021.",
    credibility: 89, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 20, source: "AARO / Corbell Leak",
    tags: ["USO", "Navy", "Radar Confirmed", "Pyramid Shape"],
    videoId: "JXwP8AvIDWQ",
    videoTitle: "USS Omaha — Sphere USO Footage (2019)",
    videoSource: "Released by Jeremy Corbell / confirmed authentic by Pentagon, 2021",
  },
  {
    id: "INC-009",
    title: "Stephenville Lights",
    date: "2008-01-08",
    location: "Stephenville, Texas",
    country: "USA",
    lat: 32.22, lng: -98.20,
    shape: "Large Solid Object",
    duration: "10 minutes",
    description: "Multiple witnesses including pilots, police, and business owners reported a mile-long silent object with lights moving toward President Bush's Crawford Ranch. MUFON radar analysis found object on FAA radar data moving at 1,900mph. F-16s scrambled but failed to intercept.",
    credibility: 83, classification: "Unexplained", military: false, radarConfirmed: true,
    witnesses: 200, source: "MUFON / FAA Radar Analysis",
    tags: ["Radar Confirmed", "F-16 Scramble", "Mass Witness"],
  },
  {
    id: "INC-010",
    title: "Avi Loeb — 'IM1' Meteor Anomaly",
    date: "2014-01-08",
    location: "Pacific Ocean, Papua New Guinea",
    country: "INT",
    lat: -2.1, lng: 147.6,
    shape: "Metallic Fragments",
    duration: "N/A",
    description: "Harvard physicist Avi Loeb led expedition to recover fragments of 2014 meteor (IM1) that USAF confirmed was of interstellar origin. Iron spherules with unusual BeLaU composition recovered. Some spherules contained alloys not found in known meteorites, solar system bodies, or Earth's crust.",
    credibility: 79, classification: "Atmospheric / Unknown Material", military: false, radarConfirmed: false,
    witnesses: 1, source: "Harvard / USAF DoD Confirmation",
    tags: ["Interstellar", "Material Evidence", "Scientific"],
  },
  {
    id: "INC-011",
    title: "Turkish Airlines Radar Encounter",
    date: "2022-09-12",
    location: "Airspace over Ankara, Turkey",
    country: "Turkey",
    lat: 39.92, lng: 32.85,
    shape: "Cylindrical",
    duration: "8 minutes",
    description: "Commercial pilot and ATC radar both tracked an unknown cylindrical object at 38,000ft maintaining parallel course to Turkish Airlines flight TK-881. Object made no radio contact and showed no transponder signal. Turkish Air Force launched investigation but never released findings.",
    credibility: 74, classification: "Radar Anomaly", military: false, radarConfirmed: true,
    witnesses: 3, source: "Turkey Civil Aviation Authority",
    tags: ["Aviation", "ATC Radar", "International"],
  },
  {
    id: "INC-012",
    title: "AARO Report — 171 New Cases",
    date: "2023-03-20",
    location: "Various — Worldwide",
    country: "USA",
    lat: 38.9, lng: -77.04,
    shape: "Various",
    duration: "Various",
    description: "AARO (All-domain Anomaly Resolution Office) released its first historical report documenting 171 new UAP cases added to the 144 from the original 2021 Pentagon report. 26 cases showed potential advanced technology characteristics. 163 remained unresolved. Report submitted to Congress per NDAA 2023.",
    credibility: 99, classification: "Official Government Report", military: true, radarConfirmed: true,
    witnesses: 0, source: "AARO / Congress",
    tags: ["Official", "AARO", "Congressional"],
  },
  {
    id: "INC-013",
    title: "Washington D.C. UFO Scare",
    date: "1952-07-19",
    location: "Washington D.C. / Andrews AFB",
    country: "USA",
    lat: 38.85, lng: -76.92,
    shape: "Luminous Orbs",
    duration: "Multiple nights",
    description: "Multiple unknown objects tracked on radar at Washington National Airport and Andrews AFB for two consecutive weekends. USAF scrambled F-94 jets — objects outran interceptors. Air Traffic Controller Ed Nugent first detected the returns. Largest peacetime UFO press conference in US history followed. Objects appeared on radar, visual, and ground observation simultaneously.",
    credibility: 92, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 300, source: "USAF / CAA Radar Records",
    tags: ["Radar Confirmed", "USAF Scramble", "Mass Witness", "Historical"],
  },
  {
    id: "INC-014",
    title: "Belgian UFO Wave — F-16 Radar Lock",
    date: "1990-03-30",
    location: "Belgian Airspace, near Wavre",
    country: "Belgium",
    lat: 50.72, lng: 4.61,
    shape: "Large Triangle",
    duration: "75 minutes",
    description: "Two Belgian Air Force F-16s scrambled to intercept unknown triangular object tracked by ground radar at Glons and Semmerzake. Object locked by radar nine times — each time it performed evasive maneuvers in under a second, dropping from 10,000ft to 500ft and accelerating from 150mph to 1,100mph instantaneously. 13,500 civilian witnesses over 5-month wave. Belgian Minister of Defence publicly confirmed incident.",
    credibility: 94, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 13500, source: "Belgian Air Force / Minister of Defence",
    tags: ["F-16 Radar Lock", "Military", "Mass Witness", "Triangle", "International"],
  },
  {
    id: "INC-015",
    title: "Tehran UFO Intercept",
    date: "1976-09-19",
    location: "Airspace over Tehran, Iran",
    country: "Iran",
    lat: 35.69, lng: 51.39,
    shape: "Brilliant Orb",
    duration: "~2 hours",
    description: "Iranian Air Force scrambled two F-4 Phantom jets after multiple civilians reported a brilliant object. Both aircraft experienced full electronics and weapons-system failure when attempting to engage. Object ejected a smaller object toward one jet; crew prepared to fire then systems died. DIA and NSA documented the incident. Declassified DIA report called it an 'outstanding' UAP case with multiple platform confirmation.",
    credibility: 91, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 20, source: "DIA / NSA Declassified Report",
    tags: ["Electronics Failure", "Military", "DIA Report", "Weapons Lockout", "International"],
  },
  {
    id: "INC-016",
    title: "Kecksburg Crash & Recovery",
    date: "1965-12-09",
    location: "Kecksburg, Pennsylvania",
    country: "USA",
    lat: 40.18, lng: -79.46,
    shape: "Acorn-Shaped Object",
    duration: "Hours",
    description: "A large fireball was observed over six US states and Canada. A bell-shaped metallic object embedded in the forest near Kecksburg. US Army cordoned off the area. Witnesses reported seeing the object loaded onto a flatbed truck. NASA internal documents obtained via lawsuit reference the object. NASA concluded it may be a Soviet satellite but never provided the hardware for verification.",
    credibility: 77, classification: "Unexplained", military: true, radarConfirmed: false,
    witnesses: 400, source: "USAF / NASA FOIA Documents",
    tags: ["Recovery Operation", "Military Cordon", "FOIA", "Multi-State Fireball"],
  },
  {
    id: "INC-017",
    title: "Socorro Lonnie Zamora Landing",
    date: "1964-04-24",
    location: "Socorro, New Mexico",
    country: "USA",
    lat: 34.06, lng: -106.89,
    shape: "Oval / Egg-Shaped",
    duration: "~8 minutes",
    description: "Police officer Lonnie Zamora observed a shiny egg-shaped object on legs with two small figures nearby. Object rose with a roar and blue flame, then flew away silently. Physical evidence: four landing pad impressions, burned brush, scorched soil. FBI and US Army investigated. J. Allen Hynek called it one of the best documented landing cases with physical evidence.",
    credibility: 89, classification: "Unexplained", military: false, radarConfirmed: false,
    witnesses: 1, source: "FBI / US Army / USAF Project Blue Book",
    tags: ["Physical Evidence", "Law Enforcement", "Landing", "Project Blue Book"],
  },
  {
    id: "INC-018",
    title: "Shag Harbour USO Incident",
    date: "1967-10-04",
    location: "Shag Harbour, Nova Scotia, Canada",
    country: "Canada",
    lat: 43.46, lng: -65.73,
    shape: "Low Flying Object",
    duration: "Multi-day",
    description: "Multiple witnesses, including an RCMP officer, saw an object crash into the ocean with a flash and yellow foam. Canadian Coast Guard, Navy divers, and RCMP investigated. Divers reported a large metallic object on the ocean floor that moved to a second location under naval observation before disappearing. The only case officially acknowledged by the Canadian government as a UAP incident with a government investigation file.",
    credibility: 85, classification: "Unexplained", military: true, radarConfirmed: false,
    witnesses: 11, source: "Canadian Government / RCMP / DND File",
    tags: ["USO", "Government Acknowledged", "Navy Divers", "Canada"],
  },
  {
    id: "INC-019",
    title: "Westall UFO — 200 Student Witnesses",
    date: "1966-04-06",
    location: "Westall, Melbourne, Australia",
    country: "Australia",
    lat: -37.93, lng: 145.09,
    shape: "Saucer / Disc",
    duration: "~20 minutes",
    description: "Over 200 students and teachers at Westall High School observed a silver-grey saucer-shaped craft descend into a field and rest briefly, then ascend rapidly. Object circled the school twice before departing at speed. Physical trace: flattened grass circle. Military vehicles arrived minutes after the incident. Students and teachers were reportedly warned not to talk about the event.",
    credibility: 83, classification: "Unexplained", military: false, radarConfirmed: false,
    witnesses: 200, source: "Multiple Student / Teacher Testimonies",
    tags: ["Mass Witness", "Physical Trace", "Australia", "School Incident"],
  },
  {
    id: "INC-020",
    title: "Ariel School UFO Landing — Zimbabwe",
    date: "1994-09-16",
    location: "Ariel School, Ruwa, Zimbabwe",
    country: "Zimbabwe",
    lat: -17.88, lng: 31.13,
    shape: "Disc with Beings",
    duration: "15 minutes",
    description: "62 schoolchildren at Ariel School reported a silver disc landed in a field near the school during recess. Two small beings with large eyes were seen near the craft. Harvard psychiatrist Dr. John Mack investigated extensively and found the children's testimonies independent and credible. Children drew consistent descriptions of beings and craft. No adult supervision during the event.",
    credibility: 78, classification: "Close Encounter", military: false, radarConfirmed: false,
    witnesses: 62, source: "Dr. John Mack (Harvard) / Cynthia Hind Investigation",
    tags: ["Close Encounter", "Harvard Investigation", "Children Witnesses", "Africa"],
  },
  {
    id: "INC-021",
    title: "Lubbock Lights — Texas Tech Professors",
    date: "1951-08-25",
    location: "Lubbock, Texas",
    country: "USA",
    lat: 33.58, lng: -101.85,
    shape: "V-Formation of Lights",
    duration: "Multiple nights",
    description: "Four Texas Tech professors simultaneously photographed and observed a perfect semicircle of bluish-green lights passing overhead at speed estimated at 1,800mph. Carl Hart Jr. photographed five formations. USAF investigated under Project Blue Book and found the photographs genuine. The formation displayed precise geometric spacing inconsistent with any known natural phenomenon or aircraft of the era.",
    credibility: 81, classification: "Unexplained", military: false, radarConfirmed: false,
    witnesses: 50, source: "USAF Project Blue Book",
    tags: ["Scientific Witnesses", "Photographs", "Formation", "Project Blue Book"],
  },
  {
    id: "INC-022",
    title: "RB-47 UFO Intercept — Military Aircraft",
    date: "1957-09-19",
    location: "Texas to Oklahoma, USA",
    country: "USA",
    lat: 33.20, lng: -97.13,
    shape: "Luminous Object",
    duration: "1.5 hours",
    description: "USAF RB-47 electronic warfare aircraft tracked an unknown object for over an hour across four states. Object registered on the aircraft's own ECM system, on ground radar, and visually by multiple crew members simultaneously. Object appeared, disappeared, and reappeared — matching these transitions on all three sensors simultaneously. Classified until obtained through FOIA. Dr. James McDonald called it the best documented military radar-visual case on record.",
    credibility: 93, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 6, source: "USAF Classified Documents / FOIA Release",
    tags: ["Multi-Sensor", "Military", "FOIA", "Radar-Visual Simultaneous"],
  },
  {
    id: "INC-023",
    title: "Hudson Valley — 5,000 Witnesses",
    date: "1983-03-24",
    location: "Hudson Valley, New York",
    country: "USA",
    lat: 41.71, lng: -73.93,
    shape: "Boomerang / V-Shape",
    duration: "Years (1982–1986)",
    description: "Over 5,000 witnesses in New York's Hudson Valley reported massive V or boomerang-shaped objects moving silently at low altitude over a 5-year period. Objects were the size of multiple football fields. Witness pool included IBM scientists, police officers, and a Taconic Parkway official. Objects shut down the Indian Point Nuclear Plant's security system in one documented incident. NICAP investigated.",
    credibility: 82, classification: "Unexplained", military: false, radarConfirmed: true,
    witnesses: 5000, source: "NICAP / J. Allen Hynek Center",
    tags: ["Mass Witness", "Nuclear Proximity", "Formation", "Multi-Year Wave"],
  },
  {
    id: "INC-024",
    title: "Aguadilla Puerto Rico USO",
    date: "2013-04-25",
    location: "Rafael Hernández Airport, Aguadilla, Puerto Rico",
    country: "USA",
    lat: 18.50, lng: -67.13,
    shape: "Pink-Red Sphere",
    duration: "~3 minutes",
    description: "US Customs and Border Protection aircraft filmed a pink-reddish sphere traveling at 120mph near the airport runway. Object entered the ocean without slowing, traveled through the water, re-emerged, and then split into two objects. Leaked to Scientific Coalition for UFOlogy. Analysis by 15 scientists concluded the object displayed trans-medium capability with no conventional explanation.",
    credibility: 84, classification: "Unexplained", military: true, radarConfirmed: false,
    witnesses: 3, source: "US CBP Thermal Camera / SCU Analysis",
    tags: ["USO", "Trans-Medium", "Government Camera", "Thermal Footage", "Puerto Rico"],
  },
  {
    id: "INC-025",
    title: "Colares UFO Flap — Operation Saucer",
    date: "1977-10-01",
    location: "Colares Island, Pará, Brazil",
    country: "Brazil",
    lat: -0.93, lng: -47.36,
    shape: "Various — Cylinders & Discs",
    duration: "3 months",
    description: "Hundreds of residents of Colares Island reported being hit by beams of light from objects overhead, causing radiation burns, unconsciousness, and hair loss. Brazilian Air Force launched Operation Saucer (Operação Prato), sending aircraft to observe and document. Colonel Uyrangê Hollanda led investigation and photographed the objects. 15 people required medical treatment. Brazilian government later partially declassified the files.",
    credibility: 80, classification: "Unexplained", military: true, radarConfirmed: false,
    witnesses: 500, source: "Brazilian Air Force / Operation Saucer Files",
    tags: ["Radiation Effects", "Military Investigation", "Brazil", "Mass Witness", "Physical Injury"],
  },
  {
    id: "INC-026",
    title: "Frederick Valentich Disappearance",
    date: "1978-10-21",
    location: "Bass Strait, Victoria, Australia",
    country: "Australia",
    lat: -39.5, lng: 145.5,
    shape: "Long Metallic Object",
    duration: "6 minutes (final transmission)",
    description: "Pilot Frederick Valentich radioed Melbourne ATC reporting an unidentified aircraft following his Cessna 182. 'It's not an aircraft… it has a green light… it's hovering above me.' His transmission ended with 17 seconds of metallic scraping sound. Neither Valentich nor his aircraft were ever found. Melbourne ATC confirmed no other aircraft in the area. A coastal witness photographed an unusual object over Bass Strait that day.",
    credibility: 87, classification: "Missing — Unexplained", military: false, radarConfirmed: false,
    witnesses: 2, source: "Australian Department of Transport / ATSB",
    tags: ["Pilot Disappearance", "ATC Recording", "Missing Aircraft", "Australia"],
  },
  {
    id: "INC-027",
    title: "Battle of Los Angeles",
    date: "1942-02-25",
    location: "Los Angeles, California",
    country: "USA",
    lat: 34.05, lng: -118.24,
    shape: "Large Round Object",
    duration: "Several hours",
    description: "One month after Pearl Harbor, USAAF anti-aircraft batteries fired over 1,400 rounds at objects over Los Angeles. Multiple large round objects were reported by observers and photographed by newspapers. Secretary of the Navy Frank Knox initially dismissed it as 'war nerves.' Secretary of War Stimson said there were unidentified objects. The 37th Coast Artillery Brigade reported direct hits with no debris ever found.",
    credibility: 75, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 10000, source: "USAAF Records / LA Times Archives",
    tags: ["WWII", "Anti-Aircraft Fire", "No Debris", "Historical", "Mass Witness"],
  },
  {
    id: "INC-028",
    title: "Levelland Vehicle Interference Cases",
    date: "1957-11-02",
    location: "Levelland, Texas",
    country: "USA",
    lat: 33.58, lng: -102.37,
    shape: "Egg-Shaped / Glowing",
    duration: "~2 hours",
    description: "At least 9 independent motorists on different roads reported their vehicles' engines stalled and headlights extinguished when a large glowing egg-shaped object appeared nearby. Engines restarted after object departed. USAF investigated but concluded it was lightning and ball lightning despite no storm that night. Project Blue Book's own consultant J. Allen Hynek called the Air Force's explanation 'laughable.'",
    credibility: 84, classification: "Unexplained", military: false, radarConfirmed: false,
    witnesses: 9, source: "USAF Project Blue Book / Local Sheriff Reports",
    tags: ["Vehicle Interference", "EMF Effect", "Multiple Independent Witnesses", "Project Blue Book"],
  },
  {
    id: "INC-029",
    title: "Nimitz Strike Group — Extended Operation",
    date: "2004-11-10",
    location: "Pacific Ocean — 250mi SW of San Diego",
    country: "USA",
    lat: 31.9, lng: -122.1,
    shape: "Multiple Objects",
    duration: "5 days",
    description: "Prior to the famous Tic-Tac encounter, USS Princeton's SPY-1B radar tracked multiple objects for 5 consecutive days operating at extreme altitudes and performing maneuvers. Objects would descend from 80,000ft to sea level in seconds and hover. The Tic-Tac encounter on Nov 14 was the culmination. USS Louisville (SSN-724) also reported acoustic anomalies. Deputy Secretary of Defense confirmed operations.",
    credibility: 96, classification: "Unexplained", military: true, radarConfirmed: true,
    witnesses: 40, source: "Pentagon / USS Princeton Deck Logs",
    tags: ["Multi-Day Operation", "Navy", "SPY-1B Radar", "Submarine Acoustic"],
  },
  {
    id: "INC-030",
    title: "David Fravor — Senate Intelligence Testimony",
    date: "2023-07-26",
    location: "U.S. Senate, Washington D.C.",
    country: "USA",
    lat: 38.89, lng: -77.00,
    shape: "N/A — Congressional Record",
    duration: "N/A",
    description: "Commander David Fravor (USS Nimitz Tic-Tac pilot), Ryan Graves, and former intelligence official David Grusch testified under oath before the Senate Intelligence Committee. Grusch testified the US government possesses non-human craft and biological remains. Fravor reiterated the Tic-Tac exceeded all known technology. All three confirmed the UAP phenomenon is real and under-reported due to stigma and classification.",
    credibility: 100, classification: "Congressional Testimony", military: true, radarConfirmed: false,
    witnesses: 3, source: "U.S. Senate Intelligence Committee — Public Record",
    tags: ["Congressional Testimony", "Under Oath", "Grusch Whistleblower", "NHI Claim"],
    videoId: "uts5SGN7key",
    videoTitle: "UAP Congressional Hearing — Fravor, Graves, Grusch Testimony (2023)",
    videoSource: "C-SPAN / U.S. Senate — Official Public Record, July 26 2023",
  },
]


export const INSIGHTS = [
  { stat: "60.9%", label: "of 79,621 NUFORC reports occur between 8pm–2am — computed from real hourly data, not estimated" },
  { stat: "56%",   label: "of sightings last under 5 minutes — making detailed observation extremely difficult for witnesses" },
  { stat: "10.4%", label: "of reports describe triangle-shaped objects — triple the rate seen in the 1980s decade" },
  { stat: "1,845", label: "reports contain explicit military context (AFB, radar, pilot, intercept) — 2.3% of all records" },
  { stat: "1.6×",  label: "more reports in summer (Jun–Aug) vs. winter (Dec–Feb) — seasonal pattern computed from month data" },
  { stat: "207",   label: "reports explicitly describe physics violations (no propulsion, no wings, defied physics) — 0.3% of corpus" },
]

export const CLASSIFICATIONS = [
  { label: "Unexplained",        count: 171, color: "#ef4444", pct: 38 },
  { label: "Atmospheric",        count: 67,  color: "#f59e0b", pct: 15 },
  { label: "Radar Anomaly",      count: 89,  color: "#06b6d4", pct: 20 },
  { label: "Drone / Aircraft",   count: 112, color: "#64748b", pct: 25 },
  { label: "Unknown Material",   count: 8,   color: "#00ff88", pct: 2  },
]

export const HOTSPOTS = [
  // USA — Military / Government
  { lat: 33.77, lng: -119.5,  name: "USS Nimitz Zone",          intensity: 5 },
  { lat: 31.9,  lng: -122.1,  name: "Nimitz Extended Operation", intensity: 5 },
  { lat: 31.5,  lng: -74.2,   name: "East Coast Fleet Zone",    intensity: 4 },
  { lat: 47.51, lng: -111.18, name: "Malmstrom AFB",            intensity: 5 },
  { lat: 36.26, lng: -115.05, name: "Nellis AFB",               intensity: 5 },
  { lat: 37.23, lng: -115.81, name: "Area 51 Corridor",         intensity: 5 },
  { lat: 32.5,  lng: -118.8,  name: "USS Omaha Zone",           intensity: 4 },
  { lat: 32.67, lng: -117.16, name: "NAS North Island",         intensity: 4 },
  { lat: 38.85, lng: -76.92,  name: "Washington D.C. — 1952",   intensity: 4 },
  { lat: 38.89, lng: -77.00,  name: "Pentagon / AARO / Senate", intensity: 3 },
  // USA — Civilian / Historical
  { lat: 33.44, lng: -112.07, name: "Phoenix Lights",           intensity: 4 },
  { lat: 41.97, lng: -87.91,  name: "O'Hare Airport",           intensity: 3 },
  { lat: 32.22, lng: -98.20,  name: "Stephenville TX",          intensity: 3 },
  { lat: 34.06, lng: -106.89, name: "Socorro Landing",          intensity: 3 },
  { lat: 40.18, lng: -79.46,  name: "Kecksburg PA Crash",       intensity: 3 },
  { lat: 41.71, lng: -73.93,  name: "Hudson Valley NY",         intensity: 3 },
  { lat: 33.58, lng: -101.85, name: "Lubbock Lights",           intensity: 3 },
  { lat: 33.58, lng: -102.37, name: "Levelland TX Stalls",      intensity: 3 },
  { lat: 34.05, lng: -118.24, name: "Battle of Los Angeles",    intensity: 4 },
  { lat: 33.20, lng: -97.13,  name: "RB-47 Intercept Zone",     intensity: 4 },
  { lat: 18.50, lng: -67.13,  name: "Aguadilla Puerto Rico",    intensity: 3 },
  { lat: 63.5,  lng: -148.0,  name: "Alaska Air Corridor",      intensity: 3 },
  // International
  { lat: 52.09, lng: 1.44,    name: "Rendlesham Forest",        intensity: 4 },
  { lat: 50.72, lng: 4.61,    name: "Belgian Wave — F-16 Zone", intensity: 4 },
  { lat: 35.69, lng: 51.39,   name: "Tehran F-4 Intercept",     intensity: 4 },
  { lat: 39.92, lng: 32.85,   name: "Ankara UAP Zone",          intensity: 2 },
  { lat: 43.46, lng: -65.73,  name: "Shag Harbour Canada",      intensity: 3 },
  { lat: -37.93, lng: 145.09, name: "Westall Melbourne",        intensity: 3 },
  { lat: -39.5,  lng: 145.5,  name: "Valentich Disappearance",  intensity: 3 },
  { lat: -17.88, lng: 31.13,  name: "Ariel School Zimbabwe",    intensity: 3 },
  { lat: -0.93,  lng: -47.36, name: "Colares Brazil Flap",      intensity: 4 },
  { lat: -2.1,   lng: 147.6,  name: "IM1 Recovery Zone",        intensity: 2 },
]
